version: "3.8"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
